<?php
// Prepare the resource class query.
if (isset($query['resource_class_id'])) {
    $resourceClassId = $query['resource_class_id'] ;
} else {
    $resourceClassId = null;
}
?>

<div class="field row">
    <div class="field-meta col-12 col-md-4">
        <label for="resource_class_id"><?php echo $this->translate('Search by class'); ?></label>
    </div>
    <div class="inputs col-12 col-md-8">
        <?php echo $this->resourceClassSelect([
            'name' => 'resource_class_id',
            'attributes' => ['id' => 'resource_class_id', 'value' => $resourceClassId]
        ]); ?>
    </div>
</div>
