<?php
// Prepare the site query.
if (isset($query['site_id'])) {
    $siteId = $query['site_id'];
} else {
    $siteId = null;
}
?>
<div class="field row">
    <div class="field-meta col-12 col-md-4">
        <label for="site_id"><?php echo $this->translate('Search through an exhibit'); ?></label>
    </div>
    <div class="inputs col-12 col-md-8">
        <select name="site_id" id="site_id">
            <option value>Select exhibit...</option>
            <?php
            $defaultSiteId = $this->setting('default_site');
            $defaultSiteResponse = $this->api()->read('sites', $defaultSiteId);
            $defaultSite = $defaultSiteResponse->getContent();
            $siblings = $this->api()->search('sites')->getContent();
            foreach($siblings as $sibling):
                if($sibling->id() != $defaultSiteId) {
                    echo '<option value="'.$sibling->id().'">' . $sibling->title() . '</option>';
                }
            endforeach;
            ?>
        </select>
    </div>
</div>
