<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/advanced-search.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));


$query = isset($query) ? $query : null;
$partials = [
    // 'common/advanced-search/resource-class',
    'common/advanced-search/site-pool',
    'common/advanced-search/properties',
];
$filterResults = $this->trigger(
    'view.advanced_search',
    [
        'query' => $query,
        'resourceType' => isset($resourceType) ? $resourceType : null,
        'partials' => $partials,
    ],
    true
);
$partials = $filterResults['partials'];
?>

<div class="advanced-search-content">
<?php
foreach ($partials as $partial) {
    if($partial != 'common/advanced-search/item-sets'):
        echo $this->partial($partial, ['query' => $query]);
    endif;
}
?>
</div>