<div class="pagination">
<?php if ($totalCount): ?>
    <span><?php echo $currentPage . ' of ' . $pageCount; ?></span>
    <?php if ($currentPage != 1): ?>
    <?php echo $this->hyperlink('', $previousPageUrl, ['class' => 'previous o-icon-prev button', 'title' => $this->translate('Previous')]); ?>
    <?php endif; ?>

    
    <?php if ($currentPage < $pageCount): ?>
    <?php echo $this->hyperlink('', $nextPageUrl, ['class' => 'next o-icon-next button', 'title' => $this->translate('Next')]); ?>
    <?php endif; ?>
    <?php
    $from = $offset + 1;
    $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
    ?>
    <span class="row-count">(<?php echo sprintf($this->translate('%s–%s of %s'), $from, $to, $totalCount); ?>)</span>
<?php else: ?>
    <?php echo $this->translate('0 results'); ?>
<?php endif; ?>
</div>
