<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

// foreach($itemMedia as $media) {
	// echo $media->type();
// }
?>
<div class="col col-12">
    <div class="blocks">
        <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    </div>
</div>
<div class="col col-12">
    <?#php $this->trigger('view.show.before'); ?>
    <?php $this->trigger('view.show.after'); ?>
</div>
<div class="col col-8">
    <?php $valOptions = ['hideVocabulary' => ['dcterms:identifier']]; ?>
    <div class="properties">
        <?php echo $item->displayValues($valOptions); ?>
    </div>
</div>
<?php
// $page = $this->params()->fromQuery('page', 1);
// $property = $this->params()->fromQuery('property');
// $subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?#php if ($subjectValues): ?>
<!-- <div id="item-linked">
    <h3><?#php echo $this->translate('Linked resources'); ?></h3>
    <?#php echo $subjectValues; ?>
</div> -->
<?#php endif; ?>
