<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

?>
<div class="col col-12">
    <div class="blocks">
        <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    </div>
</div>
<div class="col col-12">
    <?php $this->trigger('view.show.after'); ?>
</div>
<div class="col col-8">
    <?php $valOptions = ['hideVocabulary' => ['dcterms:identifier']]; ?>
    <div class="properties">
        <?php echo $item->displayValues($valOptions); ?>
    </div>
</div>