<?php
$escape = $this->plugin('escapeHtml');
$setting = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
// $this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap-grid.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');

$this->headScript()->prependFile($this->assetUrl('js/ginling-public-script.js'));
$this->headScript()->prependFile($this->assetUrl('js/jquery-3.3.1.min.js'));
// $this->headScript()->prependFile($this->assetUrl('js/default.js'));
// $this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));


$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->partial('common/user-bar', ['site' => $site]);
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
		<link rel="apple-touch-icon" sizes="180x180" href="<?= $this->assetUrl('favicons/apple-touch-icon.png'); ?>"/>
		<link rel="icon" type="image/png" sizes="32x32" href="<?= $this->assetUrl('favicons/favicon-32x32.png'); ?>"/>
		<link rel="icon" type="image/png" sizes="16x16" href="<?= $this->assetUrl('favicons/favicon-16x16.png"'); ?>"/>
		<link rel="manifest" href="<?= $this->assetUrl('favicons/site.webmanifest');?>"/>
		<link rel="mask-icon" href="<?= $this->assetUrl('favicons/safari-pinned-tab.svg'); ?>" color="#ffffff"/>
		<meta name="msapplication-TileColor" content="#da532c"/>
		<meta name="theme-color" content="#ffffff"/>
	</head>

	<?php
	echo $this->htmlElement('body');
	echo $this->elements[$this->element];
	?>
		<?php echo $userBar; ?>
		<header class="main max-width">
			<div class="row">
				<div class="site-image col col-12 col-md-4 d-none d-md-block">
					<a href="<?php echo $this->url('top'); ?>">
						<img src="<?= $this->assetUrl('img/header.png') ?>" title="Ginling College">
					</a>
				</div>
				<div class="site-title col col-12 col-md-8">
					<div class="row">
						<nav class="top">
							<?php $defaultSiteId = $this->setting('default_site');
							$defaultSiteResponse = $this->api()->read('sites', $defaultSiteId);
							$defaultSite = $defaultSiteResponse->getContent(); ?>
							<a href="<?= $this->url('top') ?>">
								<h1>
									<?= $this->setting('installation_title', 'Omeka S') ?>
								</h1>
							</a>

							<div class="global">
								<div class="mobile-site-title">
									<?= $this->setting('installation_title', 'Omeka S'); ?>
								</div>
								<?= $defaultSite->publicNav(); ?>
								<?= $this->partial('common/search-form'); ?>
							</div>
						</nav>
						<nav class="fixed">
							<div class="max-width">
								<div class="row">
									<div class="col col-4 site-title">
										<a href="<?= $this->url('top') ?>">
											<h1>
												<?= $this->setting('installation_title', 'Omeka S') ?>
											</h1>
										</a>
									</div>
									<div class="col col-8">
										<div class="global">
											<div class="mobile-site-title">
												<?= $this->setting('installation_title', 'Omeka S'); ?>
											</div>
											<?= $defaultSite->publicNav(); ?>
											<?= $this->partial('common/search-form'); ?>
										</div>
									</div>
								</div>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</header>
		<div id="content" class="max-width" role="main">
			<div class="row">
				<?php
				$path = $_SERVER["REQUEST_URI"];
				$parts = explode( '/', $path );
				?>
				<?php if( array_key_exists( '2', $parts ) && substr( $parts['2'], 0, 4 ) != 'item'): ?>
					<div class="col col-12 col-md-4">
					<?php if($site->id() == $defaultSiteId): ?>
						<nav class="side row home">
					<?php else: ?>
						<nav class="side row"><h2><?= $site->title(); ?></h2>
					<?php endif; ?>
					<div class="local"><?= $site->publicNav();?></div>
					</div><div class="col col-12 col-md-8">
				<?php endif; ?>
				<?= $this->content; ?>
				</div>
			</div>
		</div>
		<footer class="footer max-width">
			<div class="row mx-auto">
				<a href="https://www.barnard.edu">
					<img src="<?= $this->assetUrl('img/barnard-logo.png') ?>" title="Barnard College">
				</a>
				<p>Copyright © <?= date('Y') ?></p>
			</div>
		</footer>
	</body>
</html>
